language: python
python:
    - '2.7'
    - '3.3'
install:
    - python setup.py install
    - pip install nose-testconfig
env:
  global:
  - secure: ZZ2hIW6D36WKyPOhLAkCcA7lqa8lV8ty8aHrJSONa83DMEbp0NasBqBpPSX0Awp3DPniNnGCn3kPIZXwx/sJuSMCKitmAu4HtYynTK2yhv+A/JJsmnBLMm1OlBZWJ6FJ9LszuZIvXSCA1MLk7QvY5olqqFp1UYEh7ep9CueL9dY=
  - secure: bMh9I7FhrQOBm5w7VwuyvyB1s2SyelIy/xHM1q1gnH5PZbua0t7DzFlhVwbXY8rXoNIiPGzJlnZ6VeAA3atObJNbkxGQmQ41ZVReT1I8M9VPHQaz/dkBW9mO+QIBchgONuciT87uAa3SmP5gxPSAP5EGNpKT7p2K6iIgzIOYB68=
  - secure: OxaTiUNIaHvRjdKOjleXTpP5h1oi2c3SHuz1joGkasMB7bEL678vT6f/Ed3faY3dwwpGnKZx4Wc5KJgLKHm3GS10cmU+yH0S/kXb0uXQUye//uardM51l1/mvxyXFyHBBt8ShaUqWVV03MHfSNOBpFsPYsPx83jO3/hYBfg7Hjk=
script: nosetests
